# Generated by Django 4.1.7 on 2023-09-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='contct',
            new_name='contact',
        ),
    ]
