# Generated by Django 4.1.7 on 2023-09-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_app', '0002_rename_contct_team_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=255)),
                ('team2', models.CharField(max_length=255)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
            ],
        ),
    ]
